### PR TITLE
10000 frequency list in german dutch and spanish

### PR DESCRIPTION
**Pull request by AntonioBarral**
The spanish list is a bit smaller because I deleted the words with only one letter (which are not words in spanish)

### CODE REVIEW

**Comment by FannaIQ** [comment]
We agreed on on xml-format. Why is it in .csv?

**Comment by AntonioBarral** [comment]
We only need them to see how frequent is a word in a language, therefore they are used only in the algorithm, we don't need to store them in the server. However if you want I can do it in xml I think

**Comment by FannaIQ** [comment]
The algorithm takes a vector (array) with word _objects_. The frequency of a word is something that needs to be IN the vector. The conversion TO that vector is from xml-files. So yes, it needs to be in xml

**Comment by AntonioBarral** [comment]
It should be now, I hope

**Pull request merged**
